[{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [1768] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 87\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[1768] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [11156] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 87\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[11156] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [14120] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[14120] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [3200] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[3200] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [5504] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[5504] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [6272] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[6272] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [9668] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[9668] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [9696] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[9696] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [11064] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[11064] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [10356] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[10356] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [1688] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[1688] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [1136] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[1136] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [9832] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[9832] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [7212] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[7212] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [8768] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[8768] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [3828] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[3828] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [9360] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[9360] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [8116] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[8116] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [1916] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[1916] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [10532] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[10532] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [4928] Failed to execute script docker-compose\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\docker-compose.yml\" -f \"C:\\Projetos\\2022\\RestWithASPNetUdemy\\Solution\\RestWithASPNetUdemy\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose13336654911943079889 --ansi never kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'O sistema nÒo pode encontrar o arquivo especificado.')\r\n[4928] Failed to execute script docker-compose\r\n"}]